import { useState } from 'react';
import { Bell, CheckCheck, MailOpen } from 'lucide-react';
import { useApp } from '../../context/AppContext';

type Filter = 'all' | 'unread' | 'read';
export function NotificationsModule() {
  const { activeRole, toasts, setNotificationRead, setNotificationsRead } = useApp();
  const [filter, setFilter] = useState<Filter>('all');
  const [selected, setSelected] = useState<string[]>([]);
  const all = toasts.filter((item) => !item.role || item.role === activeRole);
  const visible = all.filter((item) => filter === 'all' || (filter === 'read' ? item.read : !item.read));
  const unread = all.filter((item) => !item.read).length;
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <div className="space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-100 bg-white px-5 py-3"><div className="flex items-center gap-3"><span className="rounded-lg bg-blue-50 p-2 text-blue-700"><Bell className="h-5 w-5"/></span><div><h1 className="text-lg font-bold text-slate-900">Notificaciones</h1><p className="text-xs text-slate-500">{unread} sin leer · historial de este perfil</p></div></div><button onClick={() => setNotificationsRead(all.map((item) => item.id), true)} disabled={!unread} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold text-blue-800 disabled:opacity-40"><CheckCheck className="h-4 w-4"/>Marcar todas como leídas</button></header>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-4 py-3"><div className="flex gap-1">{([['all','Todas'],['unread','No leídas'],['read','Leídas']] as [Filter,string][]).map(([id,label]) => <button key={id} onClick={() => {setFilter(id);setSelected([]);}} aria-current={filter === id ? 'page' : undefined} className={`rounded-lg px-3 py-2 text-xs font-semibold ${filter === id ? 'bg-blue-700 text-white' : 'text-slate-600 hover:bg-blue-50'}`}>{label}{id === 'unread' && ` (${unread})`}</button>)}</div><div className="flex items-center gap-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" aria-label="Seleccionar visibles" checked={visible.length > 0 && visible.every((item) => selected.includes(item.id))} onChange={(event) => setSelected(event.target.checked ? visible.map((item) => item.id) : [])}/>Seleccionar visibles</label>{selected.length > 0 && <><button onClick={() => {setNotificationsRead(selected,true);setSelected([]);}} className="rounded-lg border bg-white px-2 py-1.5 font-semibold">Marcar leídas</button><button onClick={() => {setNotificationsRead(selected,false);setSelected([]);}} className="rounded-lg border bg-white px-2 py-1.5 font-semibold">Marcar no leídas</button></>}</div></div>
      {visible.length ? <div className="divide-y">{visible.map((item) => <article key={item.id} className={`flex items-start gap-3 px-4 py-3 ${item.read ? 'bg-white' : 'bg-blue-50/60'}`}><input type="checkbox" aria-label={`Seleccionar ${item.title}`} checked={selected.includes(item.id)} onChange={() => toggle(item.id)} className="mt-1"/><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${item.read ? 'bg-slate-300' : 'bg-blue-600'}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-slate-900">{item.title}</strong><time className="text-[11px] text-slate-500">{item.timestamp}</time></div><p className="mt-0.5 text-xs leading-5 text-slate-600">{item.message}</p></div><button onClick={() => setNotificationRead(item.id, !item.read)} className="flex shrink-0 items-center gap-1 rounded-lg px-2 py-1.5 text-xs font-semibold text-blue-700 hover:bg-blue-100" aria-label={item.read ? `Marcar ${item.title} como no leída` : `Marcar ${item.title} como leída`}>{item.read ? <MailOpen className="h-4 w-4"/> : <CheckCheck className="h-4 w-4"/>}<span className="hidden sm:inline">{item.read ? 'No leída' : 'Leída'}</span></button></article>)}</div> : <p className="p-10 text-center text-sm text-slate-500">No hay notificaciones en este filtro.</p>}
    </section>
  </div>;
}
