import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { OnboardingRucModule } from './OnboardingRucModule';
import { VaultSignatureModule } from './VaultSignatureModule';
import { Building2, FileCheck2, KeyRound, UserRound, LockKeyhole, Upload, CheckCircle2 } from 'lucide-react';

type Section = 'account' | 'tax' | 'establishment' | 'signature' | 'vault';
export const ProfileModule: React.FC<{ initialSection?: Section }> = ({ initialSection = 'account' }) => {
  const { activeRole, profile, updateProfile, accountantProfile, updateAccountantProfile, profileSetupComplete, completeProfileSetup, updateCertificate } = useApp();
  const [section, setSection] = useState<Section>(initialSection);
  const [certFileName, setCertFileName] = useState('');
  const [certPassword, setCertPassword] = useState('');
  const [certIssuer, setCertIssuer] = useState('Security Data Seguridad en Datos S.A.');
  const [certExpiry, setCertExpiry] = useState('2027-10-14');
  const [certSaved, setCertSaved] = useState(false);
  const sections: { id: Section; label: string; icon: React.ElementType }[] = [
    { id: 'account', label: 'Cuenta', icon: UserRound },
    ...(activeRole === 'CONTRIBUYENTE' ? [{ id: 'tax' as const, label: 'Datos tributarios', icon: FileCheck2 }, { id: 'establishment' as const, label: 'Establecimientos', icon: Building2 }, { id: 'signature' as const, label: 'Firma digital', icon: KeyRound }, { id: 'vault' as const, label: 'Bóveda', icon: LockKeyhole }] : [])
  ];
  const handleCertificateSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!certFileName || !certPassword) return;
    updateCertificate(certIssuer, certExpiry);
    setCertPassword('');
    setCertSaved(true);
  };
  const navButton = (item: typeof sections[number]) => {
    const Icon = item.icon;
    return <button key={item.id} type="button" aria-current={section === item.id ? 'page' : undefined} onClick={() => setSection(item.id)} className={`flex min-h-11 items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold transition-colors ${section === item.id ? 'border-blue-200 bg-blue-50 text-blue-900' : 'border-transparent bg-slate-100/80 text-slate-700 hover:bg-slate-200'}`}><Icon className="h-4 w-4"/>{item.label}</button>;
  };
  return <div className="space-y-5">
    <header className="rounded-2xl border border-slate-200/80 bg-white p-5 sm:p-6 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-blue-700">Cuenta y configuración</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{activeRole === 'CONTADOR_PROFESIONAL' ? 'Perfil profesional' : activeRole === 'SUPER_ADMIN' ? 'Perfil de administrador' : 'Perfil del contribuyente'}</h1><p className="mt-1 text-sm text-slate-600">Administra tus datos y la configuración del negocio.</p></header>
    {activeRole === 'CONTRIBUYENTE' && !profileSetupComplete && <div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><strong>Configuración pendiente.</strong> Carga el RUC, revisa los datos y configura el certificado.</div>}
    <nav aria-label="Secciones del perfil" className="flex flex-wrap gap-2">{sections.map(navButton)}</nav>
    {section === 'account' && <section className="max-w-3xl rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Datos de acceso</h2><p className="mt-1 text-sm text-slate-600">El registro e inicio de sesión se encuentran al entrar a CONT MARJO.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3"><span className="block text-xs text-slate-500">Tipo de cuenta</span><strong>{activeRole === 'CONTADOR_PROFESIONAL' ? 'Contador / estudio contable' : activeRole === 'SUPER_ADMIN' ? 'Super administrador' : 'Contribuyente'}</strong></div>{activeRole === 'CONTADOR_PROFESIONAL' ? <><label className="text-sm">Correo electrónico<input type="email" value={accountantProfile.email} onChange={(event) => updateAccountantProfile({ email: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Contador / estudio<input value={accountantProfile.displayName} onChange={(event) => updateAccountantProfile({ displayName: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Registro profesional<input value={accountantProfile.professionalLicense} onChange={(event) => updateAccountantProfile({ professionalLicense: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label></> : <><label className="text-sm">Correo electrónico<input type="email" value={profile.email} onChange={(event) => updateProfile({ email: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label>{activeRole === 'CONTRIBUYENTE' && <label className="text-sm sm:col-span-2">Razón social / nombre<input value={profile.razonSocial} onChange={(event) => updateProfile({ razonSocial: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label>}</>}</div></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'tax' && <div className="space-y-4"><OnboardingRucModule/><div className="flex justify-end"><button onClick={() => setSection('establishment')} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Continuar: establecimiento →</button></div></div>}
    {activeRole === 'CONTRIBUYENTE' && section === 'establishment' && <section className="max-w-3xl rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Establecimiento matriz</h2><p className="mb-4 text-sm text-slate-600">Confirma la información detectada del RUC.</p><label className="block text-sm">Dirección<input value={profile.direccion} onChange={(event) => updateProfile({direccion:event.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><label className="mt-4 block text-sm">Nombre comercial<input value={profile.nombreComercial} onChange={(event) => updateProfile({nombreComercial:event.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><button onClick={() => setSection('signature')} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Continuar: firma digital →</button></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'signature' && <section className="max-w-3xl rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><span className="rounded-lg bg-blue-50 p-2 text-blue-700"><KeyRound className="h-5 w-5"/></span><div><h2 className="text-lg font-bold">Firma digital</h2><p className="mt-1 text-sm text-slate-600">Adjunta aquí el certificado .PFX o .P12. Esta simulación solo muestra el estado; no guarda el archivo, la contraseña ni valida la firma.</p></div></div>
      <div className="mt-4 flex items-center gap-2 rounded-lg border p-3 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${profile.signatureConfigured ? 'bg-emerald-500' : 'bg-amber-500'}`}/><span className="font-semibold">{profile.signatureConfigured ? 'Certificado configurado en esta demo' : 'Certificado pendiente'}</span>{profile.signatureConfigured && <span className="text-slate-500">· {profile.signatureCertIssuer} · vence {profile.signatureCertExpiryDate}</span>}</div>
      <form onSubmit={handleCertificateSubmit} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Archivo del certificado (.pfx / .p12)<input required type="file" accept=".pfx,.p12" onChange={(event) => {setCertFileName(event.target.files?.[0]?.name || '');setCertSaved(false);}} className="mt-1.5 block w-full rounded-lg border border-slate-300 p-2 text-sm"/><span className="mt-1 block text-xs text-slate-500">{certFileName || 'El archivo solo se usa para mostrar la carga simulada.'}</span></label>
        <label className="text-sm font-medium">Entidad emisora<select value={certIssuer} onChange={(event) => setCertIssuer(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2"><option>Security Data Seguridad en Datos S.A.</option><option>Banco Central del Ecuador (BCE)</option><option>Consejo de la Judicatura - ICERT</option><option>ANF Autoridad de Certificación Ecuador</option><option>Uanataca Ecuador S.A.</option></select></label>
        <label className="text-sm font-medium">Fecha de vencimiento<input required type="date" value={certExpiry} onChange={(event) => setCertExpiry(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2"/></label>
        <label className="text-sm font-medium sm:col-span-2">Contraseña del certificado<input required type="password" value={certPassword} onChange={(event) => setCertPassword(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2" placeholder="Ingresa la clave solo para esta simulación"/></label>
        <div className="flex flex-wrap items-center justify-between gap-3 sm:col-span-2"><span className="text-xs text-slate-500">No uses un certificado ni contraseña reales en este prototipo.</span><button type="submit" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white"><Upload className="h-4 w-4"/>Adjuntar y revisar estado</button></div>
      </form>{certSaved && <p role="status" className="mt-3 flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Archivo {certFileName} adjuntado. Estado actualizado en la simulación; archivo descartado.</p>}
      <button onClick={() => setSection('vault')} className="mt-5 rounded-lg bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700">Continuar a bóveda →</button></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'vault' && <div className="space-y-4"><VaultSignatureModule/><div className="flex flex-col items-end gap-2">{!profile.signatureConfigured && <p className="text-right text-xs text-amber-800">Configura la firma digital para terminar el registro. Puedes hacerlo desde la sección “Firma digital”.</p>}<button disabled={!profile.signatureConfigured} onClick={() => {completeProfileSetup();setSection('account');}} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Terminar configuración</button></div></div>}
  </div>;
};
