import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { OnboardingRucModule } from './OnboardingRucModule';
import { VaultSignatureModule } from './VaultSignatureModule';
import { Building2, FileCheck2, KeyRound, UserRound, LockKeyhole, Upload, CheckCircle2 } from 'lucide-react';

type Section = 'account' | 'professional' | 'services' | 'tax' | 'establishment' | 'signature' | 'sri' | 'vault';
export const ProfileModule: React.FC<{ initialSection?: Section }> = ({ initialSection = 'account' }) => {
  const { activeRole, profile, updateProfile, configureSriAccount, accountantProfile, updateAccountantProfile, profileSetupComplete, completeProfileSetup, updateCertificate } = useApp();
  const [section, setSection] = useState<Section>(initialSection);
  const [certFileName, setCertFileName] = useState('');
  const [certPassword, setCertPassword] = useState('');
  const [certIssuer, setCertIssuer] = useState('Security Data Seguridad en Datos S.A.');
  const [certExpiry, setCertExpiry] = useState('2027-10-14');
  const [certSaved, setCertSaved] = useState(false);
  const [sriUsername, setSriUsername] = useState(profile.sriUsername);
  const [sriPassword, setSriPassword] = useState('');
  const [adminEmail, setAdminEmail] = useState('admin@contmarjo.demo');
  const sections: { id: Section; label: string; icon: React.ElementType }[] = [
    { id: 'account', label: 'Cuenta', icon: UserRound },
    ...(activeRole === 'CONTRIBUYENTE' ? [{ id: 'tax' as const, label: 'Datos tributarios', icon: FileCheck2 }, { id: 'establishment' as const, label: 'Establecimientos', icon: Building2 }, { id: 'signature' as const, label: 'Firma digital', icon: KeyRound }, { id: 'sri' as const, label: 'Cuenta del SRI', icon: FileCheck2 }, { id: 'vault' as const, label: 'Bóveda', icon: LockKeyhole }] : activeRole === 'CONTADOR_PROFESIONAL' ? [{ id: 'professional' as const, label: 'Trayectoria', icon: FileCheck2 }, { id: 'services' as const, label: 'Servicios', icon: Building2 }] : [])
  ];
  const handleCertificateSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!certFileName || !certPassword) return;
    updateCertificate(certIssuer, certExpiry);
    setCertPassword('');
    setCertSaved(true);
  };
  const navButton = (item: typeof sections[number]) => {
    const Icon = item.icon;
    return <button key={item.id} type="button" aria-current={section === item.id ? 'page' : undefined} onClick={() => setSection(item.id)} className={`flex min-h-9 items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-semibold transition-colors ${section === item.id ? 'border-blue-200 bg-blue-50 text-blue-900' : 'border-transparent bg-slate-100/80 text-slate-700 hover:bg-slate-200'}`}><Icon className="h-4 w-4"/>{item.label}</button>;
  };
  return <div className="space-y-3">
    <header className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-blue-100 bg-white px-4 py-3 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-blue-700">Cuenta y configuración</p><h1 className="text-lg font-bold tracking-tight">{activeRole === 'CONTADOR_PROFESIONAL' ? 'Perfil profesional' : activeRole === 'SUPER_ADMIN' ? 'Perfil de administrador' : 'Perfil del contribuyente'}</h1></header>
    {activeRole === 'CONTRIBUYENTE' && !profileSetupComplete && <div className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-900"><strong>Configuración pendiente.</strong> Confirma el RUC, configura la firma automática y la cuenta SRI de demostración.</div>}
    <nav aria-label="Secciones del perfil" className="flex flex-wrap gap-1">{sections.map(navButton)}</nav>
    {section === 'account' && <section className="w-full rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Datos de acceso</h2><p className="mt-1 text-sm text-slate-600">El registro e inicio de sesión se encuentran al entrar a CONT MARJO.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3"><span className="block text-xs text-slate-500">Tipo de cuenta</span><strong>{activeRole === 'CONTADOR_PROFESIONAL' ? 'Contador / estudio contable' : activeRole === 'SUPER_ADMIN' ? 'Super administrador' : 'Contribuyente'}</strong></div>{activeRole === 'CONTADOR_PROFESIONAL' ? <><label className="text-sm">Correo electrónico<input type="email" value={accountantProfile.email} onChange={(event) => updateAccountantProfile({ email: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Contador / estudio<input value={accountantProfile.displayName} onChange={(event) => updateAccountantProfile({ displayName: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Registro profesional<input value={accountantProfile.professionalLicense} onChange={(event) => updateAccountantProfile({ professionalLicense: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label></> : <><label className="text-sm">Correo electrónico<input type="email" value={activeRole === 'SUPER_ADMIN' ? adminEmail : profile.email} onChange={(event) => activeRole === 'SUPER_ADMIN' ? setAdminEmail(event.target.value) : updateProfile({ email: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label>{activeRole === 'CONTRIBUYENTE' && <label className="text-sm sm:col-span-2">Razón social / nombre<input value={profile.razonSocial} onChange={(event) => updateProfile({ razonSocial: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label>}</>}</div></section>}
    {activeRole === 'CONTADOR_PROFESIONAL' && section === 'professional' && <section className="w-full rounded-xl border border-teal-100 bg-white p-5"><h2 className="font-bold text-blue-900">Trayectoria profesional</h2><p className="mt-1 text-xs text-slate-500">Datos visibles en tu presentación de demostración.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Ciudad<input value={accountantProfile.city} onChange={(event) => updateAccountantProfile({city:event.target.value})} className="mt-1 w-full border p-2"/></label><label className="text-sm">Teléfono<input value={accountantProfile.phone} onChange={(event) => updateAccountantProfile({phone:event.target.value})} className="mt-1 w-full border p-2"/></label><label className="text-sm">Experiencia<input value={accountantProfile.experience} onChange={(event) => updateAccountantProfile({experience:event.target.value})} className="mt-1 w-full border p-2"/></label><div className="rounded-xl bg-teal-50 p-3 text-sm"><span className="block text-xs text-teal-700">Registro profesional</span><strong>{accountantProfile.professionalLicense}</strong></div></div></section>}
    {activeRole === 'CONTADOR_PROFESIONAL' && section === 'services' && <section className="w-full rounded-xl border border-teal-100 bg-white p-5"><h2 className="font-bold text-blue-900">Especialidades y servicios</h2><p className="mt-1 text-sm text-slate-600">Describe las áreas en las que puedes recibir solicitudes.</p><label className="mt-4 block text-sm">Especialidades<textarea value={accountantProfile.specialities} onChange={(event) => updateAccountantProfile({specialities:event.target.value})} rows={3} className="mt-1 w-full border p-2"/></label></section>}
    {activeRole === 'SUPER_ADMIN' && section === 'account' && <section className="w-full rounded-xl border border-blue-200 bg-white p-5"><h2 className="font-bold text-blue-900">Administración de CONT MARJO 360</h2><p className="mt-1 text-sm text-slate-600">Identidad del perfil de demostración.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Correo de administración<input type="email" value={adminEmail} onChange={(event) => setAdminEmail(event.target.value)} className="mt-1 w-full border p-2"/></label><div className="rounded-xl border bg-blue-50 p-3 text-sm"><span className="block text-xs text-slate-500">Acceso</span><strong>Superadministrador · Demo local</strong></div></div></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'tax' && <div className="space-y-4"><OnboardingRucModule/></div>}
    {activeRole === 'CONTRIBUYENTE' && section === 'establishment' && <section className="w-full rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Establecimiento matriz</h2><p className="mb-4 text-sm text-slate-600">Confirma la información detectada del RUC.</p><label className="block text-sm">Dirección<input value={profile.direccion} onChange={(event) => updateProfile({direccion:event.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><label className="mt-4 block text-sm">Nombre comercial<input value={profile.nombreComercial} onChange={(event) => updateProfile({nombreComercial:event.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'signature' && <section className="w-full rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-blue-50 p-2 text-blue-700"><KeyRound className="h-5 w-5"/></span><h2 className="text-lg font-bold">Firma digital</h2><span className={`ml-auto rounded-full px-3 py-1 text-xs font-bold ${profile.signatureConfigured ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{profile.signatureConfigured ? 'Configurada' : 'Pendiente'}</span></div>
      <p className="mt-1 text-xs text-slate-600">Adjunta un archivo de ejemplo para simular la firma automática.</p>
      <form onSubmit={handleCertificateSubmit} className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-medium">Archivo de firma · demo<input required type="file" onChange={(event) => {setCertFileName(event.target.files?.[0]?.name || '');setCertSaved(false);}} className="mt-1.5 block w-full rounded-lg border border-slate-300 p-2 text-sm"/><span className="mt-1 block text-xs text-slate-500">{certFileName || 'Cualquier archivo para la demo.'}</span></label>
        <label className="text-sm font-medium">Entidad emisora<select value={certIssuer} onChange={(event) => setCertIssuer(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2"><option>Security Data Seguridad en Datos S.A.</option><option>Banco Central del Ecuador (BCE)</option><option>Consejo de la Judicatura - ICERT</option><option>ANF Autoridad de Certificación Ecuador</option><option>Uanataca Ecuador S.A.</option></select></label>
        <label className="text-sm font-medium">Fecha de vencimiento<input required type="date" value={certExpiry} onChange={(event) => setCertExpiry(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2"/></label>
        <label className="text-sm font-medium">Contraseña de ejemplo<input required type="password" value={certPassword} onChange={(event) => setCertPassword(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2" placeholder="Clave para esta demo"/></label>
        <div className="flex flex-wrap items-center justify-end gap-3 md:col-span-2 xl:col-span-4"><button type="submit" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white"><Upload className="h-4 w-4"/>Adjuntar archivo</button></div>
      </form>{certSaved && <p role="status" className="mt-3 flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Archivo {certFileName} adjuntado. Estado actualizado en la simulación; archivo descartado.</p>}
      </section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'sri' && <section className="w-full rounded-xl border bg-white p-5"><div className="flex items-start gap-3"><span className="rounded-lg bg-blue-50 p-2 text-blue-700"><FileCheck2 className="h-5 w-5"/></span><div><h2 className="text-lg font-bold">Cuenta SRI en línea</h2><p className="mt-1 text-sm text-slate-600">Permite simular la sincronización de comprobantes del negocio. Esta app no se conecta al SRI.</p></div></div><div className={`mt-4 rounded-lg border p-3 text-sm ${profile.sriAccountConfigured ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-200 bg-amber-50 text-amber-900'}`}>{profile.sriAccountConfigured ? `Cuenta demo configurada: ${profile.sriUsername}. La sincronización sigue siendo local.` : 'Cuenta SRI pendiente de configuración.'}</div><form onSubmit={(event) => {event.preventDefault(); if (!sriUsername.trim() || !sriPassword) return; configureSriAccount(sriUsername); setSriPassword('');}} className="mt-4 grid gap-4"><label className="text-sm font-medium">Usuario o RUC<input required value={sriUsername} onChange={(event) => setSriUsername(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2" placeholder="Usuario de ejemplo" autoComplete="off"/></label><label className="text-sm font-medium">Contraseña SRI para probar (no real)<input required type="password" value={sriPassword} onChange={(event) => setSriPassword(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2" placeholder="No uses tu clave real" autoComplete="new-password"/></label><p className="text-xs text-slate-500">La contraseña se borra al confirmar; el prototipo solo conserva el usuario y el estado configurado.</p><div className="flex flex-wrap justify-between gap-2"><button type="submit" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Probar y guardar demo</button></div></form></section>}
    {activeRole === 'CONTRIBUYENTE' && section === 'vault' && <div className="space-y-4"><VaultSignatureModule/><div className="flex flex-col items-end gap-2">{(!profile.signatureConfigured || !profile.sriAccountConfigured) && <p className="text-right text-xs text-amber-800">Para completar el perfil configura firma digital y cuenta SRI desde las secciones anteriores.</p>}<button disabled={!profile.signatureConfigured || !profile.sriAccountConfigured} onClick={() => {completeProfileSetup();setSection('account');}} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Terminar configuración</button></div></div>}
    {activeRole !== 'SUPER_ADMIN' && <nav aria-label="Pasos de configuración" className="flex w-full items-center justify-between border-t pt-4"><button disabled={sections.findIndex((item) => item.id === section) === 0} onClick={() => setSection(sections[sections.findIndex((item) => item.id === section) - 1].id)} className="rounded-lg border bg-white px-4 py-2 text-sm font-bold disabled:opacity-40">← Anterior</button><span className="text-xs text-slate-500">Paso {sections.findIndex((item) => item.id === section) + 1} de {sections.length}</span><button disabled={sections.findIndex((item) => item.id === section) === sections.length - 1} onClick={() => setSection(sections[sections.findIndex((item) => item.id === section) + 1].id)} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Siguiente →</button></nav>}
  </div>;
};
