import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { VaultDocument } from '../../types';
import { FolderLock, Upload, FileText, HardDrive, Clock, CheckCircle2 } from 'lucide-react';

export const VaultSignatureModule: React.FC = () => {
  const { profile, vaultDocuments, addVaultDocument } = useApp();
  const [filter, setFilter] = useState<'ALL' | 'FIRMADO' | 'PENDIENTE_FIRMA'>('ALL');
  const [showUpload, setShowUpload] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [type, setType] = useState<VaultDocument['tipo']>('CONTRATO');
  const [description, setDescription] = useState('');
  const filtered = vaultDocuments.filter((document) => filter === 'ALL' || document.estadoFirma === filter);

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!file) return;
    const ext = file.name.split('.').pop()?.toUpperCase();
    const formato: VaultDocument['formato'] = ext === 'XML' ? 'XML' : ext === 'ZIP' ? 'ZIP' : 'PDF';
    addVaultDocument({ nombre: file.name, tipo: type, formato, tamanoMb: Number((file.size / (1024 * 1024)).toFixed(2)), estadoFirma: 'NO_REQUIERE', descripcion: description || 'Archivo de negocio añadido en la demo.' });
    setFile(null); setDescription(''); setShowUpload(false);
  };

  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase text-blue-700"><FolderLock className="h-4 w-4"/>Documentos del negocio</p><h2 className="mt-1 text-xl font-bold">Bóveda documental</h2><p className="mt-1 text-sm text-slate-600">Guarda contratos, balances, RUC y comprobantes recibidos. El certificado digital se configura en “Firma digital”.</p></div><button onClick={() => setShowUpload(true)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Upload className="h-4 w-4"/>Añadir documento</button></header>
    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border bg-white p-5"><div className="flex items-center gap-3"><HardDrive className="h-5 w-5 text-blue-600"/><div><p className="text-sm font-bold">Espacio de archivos</p><p className="text-xs text-slate-500">Límite del plan de demostración</p></div><strong className="ml-auto text-sm">{profile.storageUsed} / {profile.storageLimit}</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${Math.min(100, profile.storageUsed / profile.storageLimit * 100)}%`}}/></div><p className="mt-1 text-xs text-slate-500">Cada archivo guardado ocupa un espacio.</p></article><article className="rounded-xl border bg-blue-50 p-5"><h3 className="text-sm font-bold text-blue-950">¿Qué guardar aquí?</h3><p className="mt-2 text-sm text-blue-900">Contratos, estados financieros, documentos del RUC, anexos y comprobantes de compra. No es el lugar para cargar el certificado PFX/P12.</p></article></section>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h3 className="font-bold">Archivos guardados</h3><p className="text-xs text-slate-500">El prototipo solo registra una ficha local del archivo.</p></div><div className="flex gap-1 rounded-lg bg-slate-100 p-1">{(['ALL','FIRMADO','PENDIENTE_FIRMA'] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${filter === value ? 'bg-white shadow-sm' : 'text-slate-600'}`}>{value === 'ALL' ? 'Todos' : value === 'FIRMADO' ? 'Firmados' : 'Pendientes'}</button>)}</div></div>
      {filtered.length === 0 ? <div className="p-10 text-center"><FileText className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-2 text-sm font-semibold text-slate-700">Aún no hay archivos guardados</p><p className="text-xs text-slate-500">Añade un documento para empezar tu bóveda.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Archivo</th><th className="p-3">Categoría</th><th className="p-3">Fecha</th><th className="p-3">Tamaño</th><th className="p-3">Estado</th></tr></thead><tbody className="divide-y">{filtered.map((document) => <tr key={document.id}><td className="p-3"><span className="flex items-center gap-2"><FileText className="h-4 w-4 text-slate-400"/><span><strong className="block">{document.nombre}</strong><small className="text-slate-500">{document.descripcion}</small></span></span></td><td className="p-3">{document.tipo}</td><td className="p-3 text-slate-600">{document.fechaSubida}</td><td className="p-3">{document.tamanoMb} MB</td><td className="p-3">{document.estadoFirma === 'FIRMADO' ? <span className="inline-flex items-center gap-1 text-xs text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5"/>Marcado como firmado</span> : document.estadoFirma === 'PENDIENTE_FIRMA' ? <span className="inline-flex items-center gap-1 text-xs text-amber-700"><Clock className="h-3.5 w-3.5"/>Pendiente</span> : <span className="text-xs text-slate-500">No requiere firma</span>}</td></tr>)}</tbody></table></div>}
    </section>
    {showUpload && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div><h3 className="text-lg font-bold">Añadir archivo a la bóveda</h3><p className="text-xs text-slate-500">Demo local: no se almacena el contenido del archivo.</p></div><label className="block text-sm font-semibold">Selecciona el archivo<input required type="file" accept=".pdf,.xml,.zip,.jpg,.png" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-1.5 block w-full rounded-lg border p-2 text-sm"/></label><label className="block text-sm font-semibold">Categoría<select value={type} onChange={(event) => setType(event.target.value as VaultDocument['tipo'])} className="mt-1.5 w-full rounded-lg border p-2"><option value="CONTRATO">Contrato</option><option value="BALANCE">Balance / estado financiero</option><option value="RUC_PDF">Documento del RUC</option><option value="DECLARACION_SRI">Declaración tributaria</option><option value="FACTURA_COMPRA">Factura de compra</option><option value="COMPROBANTE_RETENCION">Comprobante de retención</option></select></label><label className="block text-sm font-semibold">Nota (opcional)<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1.5 w-full rounded-lg border p-2" rows={2}/></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowUpload(false)} className="rounded-lg border px-3 py-2 text-sm">Cancelar</button><button disabled={!file} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Guardar archivo</button></div></form></div>}
  </div>;
};
