import { closePeriod, closeYear, getCloseChecklist, reopenPeriod } from '../../../domain/accounting/closing';
import { moneyLabel, type AccountingBook } from '../../../domain/accounting/types';
import { AccountingShell } from './AccountingShell';
import { box, primary, secondary } from './AccountingUi';

function ClosingSection({ book, period, act }: { book: AccountingBook; period: AccountingBook['periods'][number]; act: (operation: (book: AccountingBook) => AccountingBook, success: string) => void }) {
  const check = getCloseChecklist(book, period.id);
  return <div className="grid gap-4 lg:grid-cols-[1fr_350px]"><section className={box}><h2 className="text-lg font-bold">Cierre mensual · {period.start.slice(0, 7)}</h2><p className="mb-4 text-sm text-slate-500">Al cerrar, no se podrán confirmar asientos con fechas de este mes.</p><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-700">Diferencia de diario</p><strong>{moneyLabel(check.difference)}</strong></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-amber-700">Borradores por revisar</p><strong>{check.drafts}</strong></div><div className="rounded-xl bg-teal-50 p-4"><p className="text-xs text-teal-700">Movimientos sin conciliar</p><strong>{check.unmatched}</strong></div></div><div className="mt-4 flex flex-wrap gap-2">{period.status === 'OPEN' ? <button className={primary} disabled={!check.ready} onClick={() => act(book => closePeriod(book, period.id), 'Período cerrado y registrado en auditoría.')}>Cerrar período</button> : <button className={secondary} onClick={() => { const reason = prompt('Motivo de reapertura'); if (reason !== null) act(book => reopenPeriod(book, period.id, reason), 'Período reabierto con motivo registrado.'); }}>Reabrir con motivo</button>}{period.start.slice(5, 7) === '12' && period.status === 'OPEN' && <button className={secondary} onClick={() => act(book => closeYear(book, Number(period.start.slice(0, 4))), 'Cierre anual registrado y diciembre cerrado.')}>Cerrar ejercicio anual</button>}</div>{!check.ready && <p className="mt-3 text-xs text-amber-800">Completa la conciliación y confirma los borradores antes de cerrar.</p>}</section><aside className={box}><h2 className="mb-3 font-bold">Historial de auditoría</h2>{book.audit.length ? book.audit.map(item => <p key={item.id} className="border-b py-2 text-xs"><strong>{item.action}</strong> · {item.detail}<span className="block text-slate-500">{new Date(item.at).toLocaleString('es-EC')}</span></p>) : <p className="text-sm text-slate-500">Sin cierres o reaperturas todavía.</p>}</aside></div>;
}

export function ClosingModule() { return <AccountingShell title="Cierres" description="Comprueba pendientes y controla el cierre del mes y del ejercicio.">{context => <ClosingSection {...context} />}</AccountingShell>; }
