import { useApp } from '../../../context/AppContext';
import { useAccounting } from '../../../context/AccountingContext';
import { moneyLabel } from '../../../domain/accounting/types';

export function ContributorReportsModule() {
  const { profile } = useApp();
  const { books } = useAccounting();
  const reports = [...(books[profile.ruc]?.publications || [])].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
  return <div className="space-y-4"><header className="rounded-2xl border border-blue-100 bg-white px-6 py-5"><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Mi empresa · {profile.ruc}</p><h1 className="text-xl font-bold text-slate-900">Reportes contables</h1><p className="text-sm text-slate-500">Estados que tu contador ha compartido contigo.</p></header>{reports.length ? reports.map(report => <article key={report.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold text-slate-900">Estados financieros · versión {report.version}</h2><p className="text-xs text-slate-500">{report.from} al {report.to} · publicado {new Date(report.publishedAt).toLocaleString('es-EC')}</p></div><button className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white" onClick={() => { const blob = new Blob([`Concepto,USD\nActivos,${(report.assetsCents / 100).toFixed(2)}\nPasivos,${(report.liabilitiesCents / 100).toFixed(2)}\nPatrimonio,${(report.equityCents / 100).toFixed(2)}\nIngresos,${(report.incomeCents / 100).toFixed(2)}\nGastos,${(report.expenseCents / 100).toFixed(2)}\nResultado,${(report.profitCents / 100).toFixed(2)}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `estados-${profile.ruc}-${report.to}.csv`; a.click(); URL.revokeObjectURL(url); }}>Descargar CSV</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Activos" value={moneyLabel(report.assetsCents)} /><Metric label="Pasivos" value={moneyLabel(report.liabilitiesCents)} /><Metric label="Patrimonio" value={moneyLabel(report.equityCents)} /><Metric label="Resultado del período" value={moneyLabel(report.profitCents)} /></div></article>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-600">Aún no hay estados compartidos. Tu contador puede publicarlos desde Contabilidad.</div>}</div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-blue-50 p-3"><p className="text-xs text-blue-700">{label}</p><p className="font-semibold text-slate-900">{value}</p></div>; }
