import { useState } from 'react';
import { getBalanceSheet, getLedger, getProfitAndLoss } from '../../../domain/accounting/reports';
import { moneyLabel, newId, type AccountingBook } from '../../../domain/accounting/types';
import { AccountingShell } from './AccountingShell';
import { box, primary } from './AccountingUi';

function StatementsSection({ book, period, act }: { book: AccountingBook; period: AccountingBook['periods'][number]; act: (operation: (book: AccountingBook) => AccountingBook, success: string) => void }) {
  const pnl = getProfitAndLoss(book, period.start, period.end); const bs = getBalanceSheet(book, period.end);
  const [detail, setDetail] = useState(''); const ledger = detail ? getLedger(book, detail, period.start, period.end) : null;
  const publish = () => act(current => { const statement = getBalanceSheet(current, period.end); if (statement.differenceCents) throw new Error('El balance no cuadra.'); const result = getProfitAndLoss(current, period.start, period.end); const version = current.publications.filter(item => item.from === period.start && item.to === period.end).length + 1; return { ...current, publications: [{ id: newId('PUB'), entityId: current.entityId, from: period.start, to: period.end, publishedAt: new Date().toISOString(), version, assetsCents: statement.assetsCents, liabilitiesCents: statement.liabilitiesCents, equityCents: statement.equityCents, incomeCents: result.incomeCents, expenseCents: result.expenseCents, profitCents: result.profitCents }, ...current.publications] }; }, 'Versión publicada para el contribuyente.');
  const row = (id: string, label: string, amount: number) => <button key={id} className="flex w-full justify-between gap-2 border-b border-slate-100 py-2 text-left text-sm hover:text-blue-700" onClick={() => setDetail(id)}><span>{label}</span><strong>{moneyLabel(amount)}</strong></button>;
  return <div className="space-y-4"><div className="grid gap-4 lg:grid-cols-2"><section className={box}><p className="text-xs font-bold uppercase text-blue-700">{period.start} al {period.end}</p><h2 className="mb-3 text-lg font-bold">Pérdidas y ganancias</h2>{pnl.rows.map(item => row(item.account.id, `${item.account.code} · ${item.account.name}`, item.amountCents))}<div className="mt-3 flex justify-between rounded-lg bg-blue-50 p-3 font-bold"><span>Resultado</span><span>{moneyLabel(pnl.profitCents)}</span></div></section><section className={box}><p className="text-xs font-bold uppercase text-blue-700">Corte: {period.end}</p><h2 className="mb-3 text-lg font-bold">Balance general</h2>{[...bs.assets, ...bs.liabilities, ...bs.equity].map(item => row(item.account.id, `${item.account.code} · ${item.account.name}`, item.amountCents))}<div className="mt-3 grid gap-1 rounded-lg bg-blue-50 p-3 text-sm font-bold"><span>Activos {moneyLabel(bs.assetsCents)}</span><span>Pasivos {moneyLabel(bs.liabilitiesCents)}</span><span>Patrimonio, incluido resultado {moneyLabel(bs.equityCents)}</span><span>Diferencia {moneyLabel(bs.differenceCents)}</span></div></section></div>{detail && ledger && <section className={box}><div className="flex justify-between"><h3 className="font-bold">Detalle · {book.accounts.find(item => item.id === detail)?.name}</h3><button onClick={() => setDetail('')}>Cerrar</button></div>{ledger.rows.map(({ entry, balanceCents }) => <p key={entry.id} className="border-b py-2 text-sm">{entry.date} · {entry.number} · {entry.description} · saldo {moneyLabel(balanceCents)}</p>)}</section>}<button className={primary} onClick={publish}>Compartir esta versión con el contribuyente</button><p className="text-xs text-slate-500">Publicadas: {book.publications.filter(item => item.from === period.start && item.to === period.end).length} versiones para este período.</p></div>;
}

export function StatementsModule() { return <AccountingShell title="Estados financieros" description="Analiza resultados y comparte una versión con el contribuyente.">{context => <StatementsSection {...context} />}</AccountingShell>; }
